# Generated by Django 4.2.7 on 2023-11-08 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=2000)),
                ('created_time', models.DateTimeField(default=datetime.datetime(2023, 11, 8, 23, 37, 45, 922326))),
                ('Status', models.IntegerField(choices=[(0, 'TODO'), (1, 'IN_PROGRESS'), (2, 'DONE')], default=0)),
            ],
        ),
    ]
